### ISSUE TITLE
Battery Charge Port (lack of) - Document

### ISSUE THREAD

**Issue by marc-gist** [strid3r21/BeeS3#2]
Just got mine, they are great thank you.  However, I had to search discord to find out that they do not charge the LiPo battery (which is fine, as its a great little inexpensive board).

Would be nice if the Tindie store, and here documented that.

Thanks again! I look forward to putting these to use.

**Comment by strid3r21** [comment]
Thanks for the feedback. I'll make a note of it on the store so there is less confusion.
