### ISSUE TITLE
Making more?

### ISSUE THREAD

**Issue by Spectre5** [strid3r21/BeeS3#4]
Are there plans to assemble more of these?  I see they are sold out on both listed stores.  Also, have you tried using them with ESPHome?  Thanks!

**Comment by strid3r21** [comment]
> Are there plans to assemble more of these?  I see they are sold out on both listed stores.  Also, have you tried using them with ESPHome?  Thanks!

Yes I've got more in the pipeline. Not sure of an ETA as I've got some client work i have to get done first. But there will be more of them available in the near future.
